### ISSUE TITLE
[FEATURE] custom webhook

### ISSUE THREAD

**Issue by celevra** [bunkerity/bunkerweb-plugins#10]
Hi,

besides slack and discord it would be nice if we could define a custom webhook

regards

**Comment by AntoOnline** [comment]
That would be great, indeed.

**Comment by fl0ppy-d1sk** [comment]
Hey @celevra @AntoOnline,

Something that will send the report in JSON format to a custom HTTP endpoint, that's it ?

**Comment by fl0ppy-d1sk** [comment]
Hello @celevra @AntoOnline,

Custom webhook plugin is now available for BW 1.5.1. More info [here](https://github.com/bunkerity/bunkerweb-plugins/tree/main/webhook).

**Comment by celevra** [comment]
Thank you












Von: Florian Pitance ***@***.***>
Gesendet: Montag, 14. August 2023 18:34
An: bunkerity/bunkerweb-plugins
Cc: Philipp Zeitschel; Mention
Betreff: Re: [bunkerity/bunkerweb-plugins] [FEATURE] custom webhook (Issue #10)







Hello 
@celevra 
@AntoOnline,
Custom webhook plugin is now available for BW 1.5.1. More info 
here.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you were mentioned.Message
 ID: ***@***.***>
