### ISSUE TITLE
[BUG] Unaccessible bunkerweb-plugins v1.1

### ISSUE THREAD

**Issue by DimitryVo** [bunkerity/bunkerweb-plugins#17]
**Plugin(s)**
All

**Description**
In documentation 1.5.1 I see link to
EXTERNAL_PLUGIN_URLS=https://github.com/bunkerity/bunkerweb-plugins/archive/refs/tags/v1.1.zip
but accessible last release is v1.0 (main). I have tried to use coraza branch of bunkerweb-plugins, but I don't see plugins (crowdsec and clamav) in BW_UI.  

**BunkerWeb version**
Version of BunkerWeb - 1.5.1.

**Comment by fl0ppy-d1sk** [comment]
Hello @DimitryVo,

v1.1 is now available. Don't hesitate to open a new issue if you find any bug.
