### ISSUE TITLE
Does Bunkerweb1.5.2 still require clamav and virtuotal API containers

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb-plugins#19]
bunkerweb officer docker-compose sample:
![图片](https://github.com/bunkerity/bunkerweb-plugins/assets/38940994/1baa1e64-1977-4545-8c77-f3534f32ff5b)

my docker-compose.yml:
![图片](https://github.com/bunkerity/bunkerweb-plugins/assets/38940994/39c52360-f97e-42b0-978f-092afd15032b)

**Comment by fl0ppy-d1sk** [comment]
Hello @andyoulovexy,

ClamAV and VT API are not needed anymore and environment variables changed more info here : 
- https://github.com/bunkerity/bunkerweb-plugins/tree/main/clamav
- https://github.com/bunkerity/bunkerweb-plugins/tree/main/virustotal
